//! Top-level `step()` orchestrating the 6 phases.
//!
//! Phase order is the same as the upstream interpreter:
//!   0. Process player moves (launch fleets).
//!   1. Production (each owned planet generates `production` ships).
//!   2. Fleet movement (advance + collisions).
//!   3. Planet movement (rotation + sweeps) and comet advance.
//!   4. Prune removed fleets, expire comets.
//!   5. Combat resolution.
//!   6. Termination check + reward population.
//!
//! Caller responsibilities:
//!   - Build `OrbitWarsState` (typically in `pybind::pylist_to_state`).
//!   - Increment `state.step` between turns; the interpreter reads but does
//!     not increment it (matches upstream where the framework appends to
//!     `env.steps` before each call).

use crate::combat::resolve_combats;
use crate::physics::{advance_comets, advance_fleets, finalize_motion, rotate_planets};
use crate::state::{Fleet, Move, OrbitWarsState};

/// Run a single turn against `state` with the given per-player actions.
pub fn step(state: &mut OrbitWarsState, actions: &[Vec<Move>]) {
    if state.done {
        return;
    }

    // Bootstrap: if planets are empty, the caller should populate them
    // (initial state is generated by the upstream Python generator and
    // injected via `pybind::pylist_to_state`). We don't generate here.
    if state.planets.is_empty() {
        return;
    }

    // Phase 0: process moves.
    // Build a planet_id → slot index once per turn so each move's planet
    // lookup is O(1) instead of O(N). Skip the map entirely when no agent
    // submitted any moves this turn (very common with random_agent's
    // ships>=20 gate during the noisy parts of an episode).
    let any_moves = actions.iter().any(|m| !m.is_empty());
    if any_moves {
        let planet_index: std::collections::HashMap<i64, usize> = state
            .planets
            .iter()
            .enumerate()
            .map(|(i, p)| (p.id, i))
            .collect();
        for (player, moves) in actions.iter().enumerate() {
            let player_id = player as i32;
            for mv in moves.iter() {
                launch_fleet(state, &planet_index, player_id, mv);
            }
        }
    }

    // Phase 1: production.
    for planet in state.planets.iter_mut() {
        if planet.owner != -1 {
            planet.ships += planet.production;
        }
    }

    // Phase 2: fleet movement (with continuous collision against planets).
    let mut outcome = advance_fleets(state);

    // Phase 3: planet movement + sweep, then comet advance + sweep.
    rotate_planets(state, &mut outcome);
    // Skip comet advance entirely when no comet groups exist (typical for
    // turns 0-49 and the 70-150 / 170-250 / ... gaps between spawns).
    let expired_comets = if state.comets.is_empty() {
        Vec::new()
    } else {
        advance_comets(state, &mut outcome)
    };

    // Phase 5: combat resolution. Must run BEFORE finalize_motion because
    // combat reads from the (still un-pruned) fleet vector through the
    // indices stored in outcome.combat_lists.
    resolve_combats(state, &outcome);

    // Phase 4 (deferred): prune removed fleets / expired comets.
    finalize_motion(state, &outcome, &expired_comets);

    // Phase 6: termination + reward.
    // Use a bitmask instead of HashSet — num_agents ≤ 4, so 4 bits suffice.
    // Short-circuit as soon as we see ≥2 distinct owners (the common case in
    // mid-game), since `terminated` only flips on alive_count <= 1.
    let max_steps_reached = state.step >= state.episode_steps - 2;
    let alive_count_le_1 = if max_steps_reached {
        // We need to compute scores anyway, defer counting until the if-block.
        false
    } else {
        let mut mask: u8 = 0;
        let mut bits: u32 = 0;
        for p in state.planets.iter() {
            if p.owner >= 0 && p.owner < 8 {
                let new_mask = mask | (1u8 << (p.owner as u8));
                if new_mask != mask {
                    mask = new_mask;
                    bits += 1;
                    if bits >= 2 {
                        break;
                    }
                }
            }
        }
        if bits < 2 {
            for f in state.fleets.iter() {
                if f.owner >= 0 && f.owner < 8 {
                    let new_mask = mask | (1u8 << (f.owner as u8));
                    if new_mask != mask {
                        mask = new_mask;
                        bits += 1;
                        if bits >= 2 {
                            break;
                        }
                    }
                }
            }
        }
        bits <= 1
    };
    let terminated = max_steps_reached || alive_count_le_1;

    if terminated {
        state.done = true;
        let n = state.num_agents;
        let mut scores = vec![0i64; n];
        for p in state.planets.iter() {
            if p.owner != -1 && (p.owner as usize) < n {
                scores[p.owner as usize] += p.ships;
            }
        }
        for f in state.fleets.iter() {
            if (f.owner as usize) < n {
                scores[f.owner as usize] += f.ships;
            }
        }
        let max_score = *scores.iter().max().unwrap_or(&0);
        state.rewards = (0..n)
            .map(|i| {
                if scores[i] == max_score && max_score > 0 {
                    1
                } else {
                    -1
                }
            })
            .collect();
    }
}

/// Sanitize and apply a single `Move`, appending a fleet on success. Mirrors
/// `process_moves` in the upstream interpreter (orbit_wars.py:480–509).
fn launch_fleet(
    state: &mut OrbitWarsState,
    planet_index: &std::collections::HashMap<i64, usize>,
    player_id: i32,
    mv: &Move,
) {
    let ships = mv.ships;
    if ships <= 0 {
        return;
    }
    let Some(&planet_slot) = planet_index.get(&mv.from_planet_id) else {
        return;
    };
    let planet = &state.planets[planet_slot];
    if planet.owner != player_id {
        return;
    }
    if planet.ships < ships {
        return;
    }
    let (sin_a, cos_a) = mv.angle.sin_cos();
    let offset = planet.radius + 0.1;
    let start_x = planet.x + cos_a * offset;
    let start_y = planet.y + sin_a * offset;
    let from_planet_id = planet.id;
    state.planets[planet_slot].ships -= ships;
    let id = state.next_fleet_id;
    state.next_fleet_id += 1;
    state.fleets.push(Fleet {
        id,
        owner: player_id,
        x: start_x,
        y: start_y,
        angle: mv.angle,
        from_planet_id,
        ships,
    });
}
