//! ChaCha12 RNG wrapper with helpers tuned to the calls the simulator makes
//! (uniform float ranges and inclusive integer ranges).
//!
//! The Rust simulator does NOT preserve bit-exact compatibility with Python's
//! `random` module — we use a portable deterministic stream (ChaCha12) seeded
//! from the Kaggle configuration. The trade-off is documented in
//! `docs/plans/rust-simulator/02-requirements.md`: parity tests run by handing
//! the Rust simulator an initial state generated by the upstream Python
//! generator, sidestepping the need for cross-language RNG agreement.

use rand::{Rng, RngCore, SeedableRng};
use rand_chacha::ChaCha12Rng;

#[derive(Clone, Debug)]
pub struct ChaChaRng {
    inner: ChaCha12Rng,
}

impl ChaChaRng {
    /// Seed the stream from a single u64 (matches `seed_from_u64`).
    pub fn seeded(seed: u64) -> Self {
        Self {
            inner: ChaCha12Rng::seed_from_u64(seed),
        }
    }

    /// `random.uniform(low, high)` — half-open `[low, high)` is fine because
    /// the upstream code never compares against the upper boundary.
    pub fn uniform(&mut self, low: f64, high: f64) -> f64 {
        self.inner.gen_range(low..high)
    }

    /// `random.randint(low, high)` — inclusive both sides.
    pub fn randint(&mut self, low: i64, high: i64) -> i64 {
        self.inner.gen_range(low..=high)
    }

    /// Underlying RngCore for callers that need direct access.
    pub fn raw(&mut self) -> &mut impl RngCore {
        &mut self.inner
    }
}
