"""Tunable constants for the case5 agent.

Verbatim copy of the configuration block from the LB1224 notebook by
Roman Tamrazov (Apache License 2.0). See `baseline/LICENSE`.
"""

from __future__ import annotations

BOARD = 100.0
CENTER_X = 50.0
CENTER_Y = 50.0
SUN_R = 10.0
MAX_SPEED = 6.0
SUN_SAFETY = 1.5
ROTATION_LIMIT = 50.0
TOTAL_STEPS = 500
SIM_HORIZON = 110
ROUTE_SEARCH_HORIZON = 60
HORIZON = SIM_HORIZON
LAUNCH_CLEARANCE = 0.1

EARLY_TURN_LIMIT = 35
OPENING_TURN_LIMIT = 75
LATE_REMAINING_TURNS = 65
VERY_LATE_REMAINING_TURNS = 28
TOTAL_WAR_REMAINING_TURNS = 42

SAFE_NEUTRAL_MARGIN = 2
CONTESTED_NEUTRAL_MARGIN = 2
INTERCEPT_TOLERANCE = 1

SAFE_OPENING_PROD_THRESHOLD = 3
SAFE_OPENING_TURN_LIMIT = 12
ROTATING_OPENING_MAX_TURNS = 14
ROTATING_OPENING_LOW_PROD = 2
FOUR_PLAYER_ROTATING_REACTION_GAP = 2
FOUR_PLAYER_ROTATING_SEND_RATIO = 0.65
FOUR_PLAYER_ROTATING_TURN_LIMIT = 11

COMET_MAX_CHASE_TURNS = 10

ATTACK_COST_TURN_WEIGHT = 0.48
SNIPE_COST_TURN_WEIGHT = 0.40
INDIRECT_VALUE_SCALE = 0.15
INDIRECT_FRIENDLY_WEIGHT = 0.35
INDIRECT_NEUTRAL_WEIGHT = 0.9
INDIRECT_ENEMY_WEIGHT = 1.25

STATIC_NEUTRAL_VALUE_MULT = 1.45
STATIC_HOSTILE_VALUE_MULT = 1.70
ROTATING_OPENING_VALUE_MULT = 0.92
HOSTILE_TARGET_VALUE_MULT = 2.05
OPENING_HOSTILE_TARGET_VALUE_MULT = 1.55
SAFE_NEUTRAL_VALUE_MULT = 1.25
CONTESTED_NEUTRAL_VALUE_MULT = 0.72
EARLY_NEUTRAL_VALUE_MULT = 1.25
COMET_VALUE_MULT = 0.65
SNIPE_VALUE_MULT = 1.15
SWARM_VALUE_MULT = 1.08
REINFORCE_VALUE_MULT = 1.35
CRASH_EXPLOIT_VALUE_MULT = 1.20
FINISHING_HOSTILE_VALUE_MULT = 1.25
BEHIND_ROTATING_NEUTRAL_VALUE_MULT = 0.90
EXPOSED_PLANET_VALUE_MULT = 1.85
BLOOD_IN_WATER_VALUE_MULT = 1.45
LET_THEM_FIGHT_PENALTY = 0.72

NEUTRAL_MARGIN_BASE = 1
NEUTRAL_MARGIN_PROD_WEIGHT = 1
NEUTRAL_MARGIN_CAP = 4
HOSTILE_MARGIN_BASE = 2
HOSTILE_MARGIN_PROD_WEIGHT = 1
HOSTILE_MARGIN_CAP = 6
STATIC_TARGET_MARGIN = 2
CONTESTED_TARGET_MARGIN = 3
FOUR_PLAYER_TARGET_MARGIN = 2
LONG_TRAVEL_MARGIN_START = 20
LONG_TRAVEL_MARGIN_DIVISOR = 4
LONG_TRAVEL_MARGIN_CAP = 5
COMET_MARGIN_RELIEF = 4
FINISHING_HOSTILE_SEND_BONUS = 2

STATIC_TARGET_SCORE_MULT = 1.18
EARLY_STATIC_NEUTRAL_SCORE_MULT = 1.30
FOUR_PLAYER_ROTATING_NEUTRAL_SCORE_MULT = 0.82
DENSE_STATIC_NEUTRAL_COUNT = 4
DENSE_ROTATING_NEUTRAL_SCORE_MULT = 0.84
SNIPE_SCORE_MULT = 1.15
SWARM_SCORE_MULT = 1.08
CRASH_EXPLOIT_SCORE_MULT = 1.08

FOLLOWUP_MIN_SHIPS = 8
LOW_VALUE_COMET_PRODUCTION = 1
LATE_CAPTURE_BUFFER = 5
VERY_LATE_CAPTURE_BUFFER = 3

DEFENSE_LOOKAHEAD_TURNS = 28
DEFENSE_COST_TURN_WEIGHT = 0.38
DEFENSE_FRONTIER_SCORE_MULT = 1.14
DEFENSE_SEND_MARGIN_BASE = 1
DEFENSE_SEND_MARGIN_PROD_WEIGHT = 1
DEFENSE_SHIP_VALUE = 0.55

REINFORCE_ENABLED = True
REINFORCE_MIN_PRODUCTION = 2
REINFORCE_MAX_TRAVEL_TURNS = 22
REINFORCE_SAFETY_MARGIN = 1
REINFORCE_MAX_SOURCE_FRACTION = 0.70
REINFORCE_MIN_FUTURE_TURNS = 40
REINFORCE_HOLD_LOOKAHEAD = 20
REINFORCE_COST_TURN_WEIGHT = 0.32

RECAPTURE_LOOKAHEAD_TURNS = 10
RECAPTURE_COST_TURN_WEIGHT = 0.50
RECAPTURE_VALUE_MULT = 0.88
RECAPTURE_FRONTIER_MULT = 1.08
RECAPTURE_PRODUCTION_WEIGHT = 0.6
RECAPTURE_IMMEDIATE_WEIGHT = 0.4

REAR_SOURCE_MIN_SHIPS = 14
REAR_DISTANCE_RATIO = 1.20
REAR_STAGE_PROGRESS = 0.80
REAR_SEND_RATIO_TWO_PLAYER = 0.60
REAR_SEND_RATIO_FOUR_PLAYER = 0.68
REAR_SEND_MIN_SHIPS = 10
REAR_MAX_TRAVEL_TURNS = 38

PARTIAL_SOURCE_MIN_SHIPS = 6
MULTI_SOURCE_TOP_K = 5
MULTI_SOURCE_ETA_TOLERANCE = 2
MULTI_SOURCE_PLAN_PENALTY = 0.97
HOSTILE_SWARM_ETA_TOLERANCE = 1
THREE_SOURCE_SWARM_ENABLED = True
THREE_SOURCE_MIN_TARGET_SHIPS = 18
THREE_SOURCE_ETA_TOLERANCE = 1
THREE_SOURCE_PLAN_PENALTY = 0.93

PROACTIVE_DEFENSE_HORIZON = 12
PROACTIVE_DEFENSE_RATIO = 0.14
MULTI_ENEMY_PROACTIVE_HORIZON = 14
MULTI_ENEMY_PROACTIVE_RATIO = 0.18
MULTI_ENEMY_STACK_WINDOW = 3
REACTION_SOURCE_TOP_K_MY = 4
REACTION_SOURCE_TOP_K_ENEMY = 4
PROACTIVE_ENEMY_TOP_K = 3

CRASH_EXPLOIT_ENABLED = True
CRASH_EXPLOIT_MIN_TOTAL_SHIPS = 8
CRASH_EXPLOIT_ETA_WINDOW = 2
CRASH_EXPLOIT_POST_CRASH_DELAY = 1

LATE_IMMEDIATE_SHIP_VALUE = 0.80
WEAK_ENEMY_THRESHOLD = 70
ELIMINATION_BONUS = 32.0
ELIMINATION_PROD_BONUS = 18.0

BEHIND_DOMINATION = -0.18
AHEAD_DOMINATION = 0.14
FINISHING_DOMINATION = 0.26
FINISHING_PROD_RATIO = 1.12
AHEAD_ATTACK_MARGIN_BONUS = 0.10
BEHIND_ATTACK_MARGIN_PENALTY = 0.04
FINISHING_ATTACK_MARGIN_BONUS = 0.10

DOOMED_EVAC_TURN_LIMIT = 24
DOOMED_MIN_SHIPS = 8

SOFT_ACT_DEADLINE = 0.82
HEAVY_PHASE_MIN_TIME = 0.16
OPTIONAL_PHASE_MIN_TIME = 0.08
HEAVY_ROUTE_PLANET_LIMIT = 32

FFA_FOCUS_PROD_RATIO = 0.60
FFA_ELIMINATION_SHIPS = 55
FFA_LET_FIGHT_MIN_SHIPS = 14
