# Adapted from "Orbit Wars 2026 - Reinforce" by sigmaborov
# https://www.kaggle.com/code/sigmaborov/lb-897-orbit-wars-2026-reinforce
# Licensed under Apache License 2.0
"""Game constants and tuning parameters ported verbatim from the notebook."""

from __future__ import annotations

from pathlib import Path
from typing import Any

BOARD: float = 100.0
CENTER_X: float = 50.0
CENTER_Y: float = 50.0
SUN_R: float = 10.0
MAX_SPEED: float = 6.0
SUN_SAFETY: float = 1.5
ROTATION_LIMIT: float = 50.0
TOTAL_STEPS: int = 500
HORIZON: int = 110
LAUNCH_CLEARANCE: float = 0.1

EARLY_TURN_LIMIT: int = 40
OPENING_TURN_LIMIT: int = 80
LATE_REMAINING_TURNS: int = 60
VERY_LATE_REMAINING_TURNS: int = 25

SAFE_NEUTRAL_MARGIN: int = 2
CONTESTED_NEUTRAL_MARGIN: int = 2
INTERCEPT_TOLERANCE: int = 1

SAFE_OPENING_PROD_THRESHOLD: int = 4
SAFE_OPENING_TURN_LIMIT: int = 10
ROTATING_OPENING_MAX_TURNS: int = 13
ROTATING_OPENING_LOW_PROD: int = 2
FOUR_PLAYER_ROTATING_REACTION_GAP: int = 3
FOUR_PLAYER_ROTATING_SEND_RATIO: float = 0.62
FOUR_PLAYER_ROTATING_TURN_LIMIT: int = 10

COMET_MAX_CHASE_TURNS: int = 10

ATTACK_COST_TURN_WEIGHT: float = 0.55
SNIPE_COST_TURN_WEIGHT: float = 0.45
INDIRECT_VALUE_SCALE: float = 0.15
INDIRECT_FRIENDLY_WEIGHT: float = 0.35
INDIRECT_NEUTRAL_WEIGHT: float = 0.9
INDIRECT_ENEMY_WEIGHT: float = 1.25

STATIC_NEUTRAL_VALUE_MULT: float = 1.4
STATIC_HOSTILE_VALUE_MULT: float = 1.55
ROTATING_OPENING_VALUE_MULT: float = 0.9
HOSTILE_TARGET_VALUE_MULT: float = 1.85
OPENING_HOSTILE_TARGET_VALUE_MULT: float = 1.45
SAFE_NEUTRAL_VALUE_MULT: float = 1.2
CONTESTED_NEUTRAL_VALUE_MULT: float = 0.7
EARLY_NEUTRAL_VALUE_MULT: float = 1.2
COMET_VALUE_MULT: float = 0.65
SNIPE_VALUE_MULT: float = 1.12
SWARM_VALUE_MULT: float = 1.05
FINISHING_HOSTILE_VALUE_MULT: float = 1.15
BEHIND_ROTATING_NEUTRAL_VALUE_MULT: float = 0.92

NEUTRAL_MARGIN_BASE: int = 2
NEUTRAL_MARGIN_PROD_WEIGHT: int = 2
NEUTRAL_MARGIN_CAP: int = 8
HOSTILE_MARGIN_BASE: int = 3
HOSTILE_MARGIN_PROD_WEIGHT: int = 2
HOSTILE_MARGIN_CAP: int = 12
STATIC_TARGET_MARGIN: int = 4
CONTESTED_TARGET_MARGIN: int = 5
FOUR_PLAYER_TARGET_MARGIN: int = 3
LONG_TRAVEL_MARGIN_START: int = 18
LONG_TRAVEL_MARGIN_DIVISOR: int = 3
LONG_TRAVEL_MARGIN_CAP: int = 8
COMET_MARGIN_RELIEF: int = 6
FINISHING_HOSTILE_SEND_BONUS: int = 3

STATIC_TARGET_SCORE_MULT: float = 1.18
EARLY_STATIC_NEUTRAL_SCORE_MULT: float = 1.25
FOUR_PLAYER_ROTATING_NEUTRAL_SCORE_MULT: float = 0.84
DENSE_STATIC_NEUTRAL_COUNT: int = 4
DENSE_ROTATING_NEUTRAL_SCORE_MULT: float = 0.86
SNIPE_SCORE_MULT: float = 1.12
SWARM_SCORE_MULT: float = 1.06

FOLLOWUP_MIN_SHIPS: int = 8
LOW_VALUE_COMET_PRODUCTION: int = 1
LATE_CAPTURE_BUFFER: int = 5
VERY_LATE_CAPTURE_BUFFER: int = 3

REAR_SOURCE_MIN_SHIPS: int = 16
REAR_DISTANCE_RATIO: float = 1.25
REAR_STAGE_PROGRESS: float = 0.78
REAR_SEND_RATIO_TWO_PLAYER: float = 0.62
REAR_SEND_RATIO_FOUR_PLAYER: float = 0.7
REAR_SEND_MIN_SHIPS: int = 10
REAR_MAX_TRAVEL_TURNS: int = 40

PARTIAL_SOURCE_MIN_SHIPS: int = 16
MULTI_SOURCE_TOP_K: int = 5
MULTI_SOURCE_ETA_TOLERANCE: int = 2
MULTI_SOURCE_PLAN_PENALTY: float = 0.85

SWARM_MIN_PARTICIPANT_SHIPS: int = 32
FULL_COMMIT_THRESHOLD_SHIPS: int = 40
FULL_COMMIT_FRACTION: float = 0.85

HOSTILE_SWARM_ETA_TOLERANCE: int = 1

THREE_SOURCE_SWARM_ENABLED: bool = True
THREE_SOURCE_MIN_TARGET_SHIPS: int = 20
THREE_SOURCE_ETA_TOLERANCE: int = 1
THREE_SOURCE_PLAN_PENALTY: float = 0.75

REINFORCE_ENABLED: bool = True
REINFORCE_MIN_PRODUCTION: int = 2
REINFORCE_MAX_TRAVEL_TURNS: int = 22
REINFORCE_SAFETY_MARGIN: int = 5
REINFORCE_VALUE_MULT: float = 1.35
REINFORCE_MAX_SOURCE_FRACTION: float = 1.0
REINFORCE_MIN_FUTURE_TURNS: int = 40

MULTI_ENEMY_PROACTIVE_HORIZON: int = 14
MULTI_ENEMY_PROACTIVE_RATIO: float = 0.22
MULTI_ENEMY_STACK_WINDOW: int = 3

PROACTIVE_DEFENSE_HORIZON: int = 12
PROACTIVE_DEFENSE_RATIO: float = 0.18

LATE_IMMEDIATE_SHIP_VALUE: float = 0.6
WEAK_ENEMY_THRESHOLD: int = 45
ELIMINATION_BONUS: float = 18.0

BEHIND_DOMINATION: float = -0.20
AHEAD_DOMINATION: float = 0.18
FINISHING_DOMINATION: float = 0.35
FINISHING_PROD_RATIO: float = 1.25
AHEAD_ATTACK_MARGIN_BONUS: float = 0.08
BEHIND_ATTACK_MARGIN_PENALTY: float = 0.05
FINISHING_ATTACK_MARGIN_BONUS: float = 0.08

DOOMED_EVAC_TURN_LIMIT: int = 24
DOOMED_MIN_SHIPS: int = 8

CRASH_EXPLOIT_ENABLED: bool = True
CRASH_EXPLOIT_MIN_TOTAL_SHIPS: int = 10
CRASH_EXPLOIT_ETA_WINDOW: int = 2
CRASH_EXPLOIT_POST_CRASH_DELAY: int = 1
CRASH_EXPLOIT_VALUE_MULT: float = 1.18

COMET_NPV_ENABLED: bool = False
COMET_NPV_MIN_USABLE_TURNS: int = 6
COMET_NPV_SHORTLIFE_FLOOR: float = 0.35
COMET_NPV_LONGLIFE_BONUS: float = 1.15
COMET_NPV_LONGLIFE_TURNS: int = 40

DYNAMIC_PROACTIVE_HORIZON_ENABLED: bool = False
DYNAMIC_PROACTIVE_HORIZON_MAX: int = 24
DYNAMIC_PROACTIVE_HORIZON_PROD_STEP: int = 3
DYNAMIC_PROACTIVE_HORIZON_PROD_CAP: int = 5

SAFE_INTERCEPT_HALF_STEP: bool = True

FINISHING_TIE_GUARD: bool = False

HARASS_ENABLED: bool = True
HARASS_MIN_TARGET_PRODUCTION: int = 2
HARASS_MIN_TARGET_SHIPS: int = 1
HARASS_MAX_TRAVEL_TURNS: int = 20
HARASS_MIN_SRC_RESERVE: int = 10
HARASS_COST_TURN_WEIGHT: float = 0.5
HARASS_VALUE_MULT: float = 1.0
HARASS_PRODUCTION_STEAL_TURNS: int = 5

OPPONENT_MODEL_ENABLED: bool = False
OM_HISTORY_WINDOW: int = 5
OM_MIN_LAUNCH_SHIPS: int = 3
OM_MIN_LAUNCH_STOCK: int = 10
OM_LAUNCH_SOURCE_BONUS: float = 0.0
OM_PREFERENCE_BONUS: float = 0.0
OM_PROACTIVE_THREAT_BOOST: float = 0.0
OM_PREDICT_HORIZON: int = 20
OM_MAX_HISTORY_ENTRIES: int = 600

OM_V2_ENABLED: bool = False
OM_PREDICTION_WEIGHT: float = 0.5
OM_PREDICT_MIN_LAUNCHES: int = 2
OM_PREDICT_APPLY_AFTER_STEP: int = 30
OM_DEFEND_PREDICTED_ATTACK: bool = True

LOOKAHEAD_ENABLED: bool = False
LOOKAHEAD_MAX_DEPTH: int = 1
LOOKAHEAD_APPLY_AFTER_STEP: int = 20
LOOKAHEAD_PREDICTION_WEIGHT: float = 0.6


def load_config(path: Path) -> dict[str, Any]:
    """Load the YAML copy of these constants for reference / future tuning."""
    import yaml

    with path.open("r", encoding="utf-8") as fh:
        data = yaml.safe_load(fh)
    if not isinstance(data, dict):
        raise ValueError(f"baseline config at {path} must be a YAML mapping")
    return data
